"""
app.py — HCRecov Streamlit App — Home Page
-----------------------------------------------
Entry point AND landing/introduction page. Sets page config, initializes
shared session_state (feed conditions + engine version toggle), and
explains the tool — no separate Introduction page needed.
"""

import streamlit as st

st.set_page_config(
    page_title="HCRecov — Hydrocarbon Recovery Sizing",
    page_icon="⚗️",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Global session state — shared feed conditions across all pages
# ---------------------------------------------------------------------------
DEFAULTS = {
    "feed_mass_kg_hr": 650.0,
    "p_feed_bar": 1.2,
    "t_feed_c": 64.0,
    "y_hc_pct": 5.0,
    "y_c3h6_pct": 4.0,
    "y_c3h8_pct": 1.0,
    "engine_version": "v2",
}

for key, val in DEFAULTS.items():
    if key not in st.session_state:
        st.session_state[key] = val

# ---------------------------------------------------------------------------
# Sidebar — Engine Version toggle (applies globally)
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Engine Version")
    st.session_state["engine_version"] = st.radio(
        "Thermodynamic model",
        options=["v2", "v3"],
        format_func=lambda v: "Run 2 — Binary Baseline" if v == "v2" else "Run 3 — Ternary Rigorous",
        index=0 if st.session_state["engine_version"] == "v2" else 1,
        help=(
            "Run 2: N2/Propylene binary feed, simpler flux/efficiency models.\n\n"
            "Run 3: N2/Propylene/Propane ternary feed, Pitzer real-gas correction, "
            "Arrhenius permeability, Kremser absorption efficiency."
        ),
    )
    st.caption(f"Active model: **{st.session_state['engine_version'].upper()}**")

# ---------------------------------------------------------------------------
# Landing / Introduction content
# ---------------------------------------------------------------------------
st.title("⚗️ HCRecov — Hydrocarbon Recovery Sizing Tool")
st.caption(
    "Industrial first-principles sizing for purge-stream monomer recovery: "
    "Polymeric Membrane · PSA Twin-Bed · Heavy Gas Absorption"
)

st.markdown(
    """
    ### What this is

    HCRecov is a first-principles industrial sizing tool for evaluating three
    competing technologies to recover gaseous hydrocarbons (propylene, with
    trace propane) from a nitrogen-rich resin purge stream.

    Rather than relying on vendor datasheets or rule-of-thumb estimates, every
    number in this app — recovery efficiency, equipment ratings, CAPEX, OPEX —
    is computed from governing thermodynamic and hydraulic equations, then
    snapped to standard industrial catalog sizes.

    ### Technologies assessed
    """
)

col1, col2, col3 = st.columns(3)
with col1:
    st.subheader("① Polymeric Membrane")
    st.markdown(
        "Selective permeation of hydrocarbons through polyimide hollow-fiber "
        "membranes, driven by a pressure differential across the fiber wall."
    )
with col2:
    st.subheader("② PSA Twin-Bed")
    st.markdown(
        "Cyclic adsorption–desorption using a competitive Langmuir isotherm "
        "on a molecular sieve bed, regenerated by depressurization."
    )
with col3:
    st.subheader("③ Heavy Gas Absorption")
    st.markdown(
        "Solubility-driven absorption of hydrocarbons into a circulating "
        "heavy oil solvent, governed by Henry's Law equilibrium."
    )

# ---------------------------------------------------------------------------
# After "Two model versions" section — bring sidebar control to main page
# ---------------------------------------------------------------------------

st.divider()

st.markdown("### Engine Version (Main Option)")
st.session_state["engine_version"] = st.radio(
    "Thermodynamic model",
    options=["v2", "v3"],
    format_func=lambda v: "Run 2 — Binary Baseline" if v == "v2" else "Run 3 — Ternary Rigorous",
    index=0 if st.session_state["engine_version"] == "v2" else 1,
    help=(
        "Run 2: N₂/Propylene binary feed, simpler flux/efficiency models.\n\n"
        "Run 3: N₂/Propylene/Propane ternary feed, Pitzer real-gas correction, "
        "Arrhenius permeability, Kremser absorption efficiency."
    ),
)
st.caption(f"Active model: **{st.session_state['engine_version'].upper()}**")

# ---------------------------------------------------------------------------
# Select model/run + technology buttons
# ---------------------------------------------------------------------------

st.markdown(
    """
    ### Select model/run

    Please select this only after choosing the model; **Run 2 is selected by default**.
    """
)

colA, colB, colC = st.columns(3)

with colA:
    if st.button("Polymeric Membrane", type="primary", key="btn_membrane"):
        st.switch_page("pages/1_Membrane.py")

with colB:
    if st.button("PSA Twin-Bed", type="primary", key="btn_psa"):
        st.switch_page("pages/2_PSA_Adsorption.py")

with colC:
    if st.button("Heavy Gas Absorption", type="primary", key="btn_absorption"):
        st.switch_page("pages/3_Absorption.py")


st.divider()

st.markdown(
    """
    ### Two model versions

    This app lets you toggle between two levels of thermodynamic rigor,
    using the **Engine Version** selector in the sidebar:

    | | **Run 2 — Binary Baseline** | **Run 3 — Ternary Rigorous** |
    |---|---|---|
    | Feed composition | N₂ + Propylene only | N₂ + Propylene + Propane |
    | Compression | Ideal-gas isentropic | Pitzer real-gas Z-factor correction |
    | Membrane permeability | Fixed Barrer value | Arrhenius temperature-corrected |
    | Absorption efficiency | Simplified NTU form | Correct Kremser equation |
    | PSA blowdown losses | Not modelled | Derived from pressure ratio |

    Both versions read from the same feed conditions (set on any technology
    page) so you can directly compare how model rigor changes the sizing
    and economics conclusions.""")

st.markdown(
    """

    ### How to use this app

    1. Go to any technology page from the sidebar.
    2. Adjust feed flow, pressure, temperature, and HC concentration using
       the sliders — these apply globally across all pages.
    3. Toggle the Engine Version in the sidebar to compare binary vs ternary
       model results.
    4. Review the component-level equipment ledger, recovery gauge, and
       process flow diagram for each technology.

    **👈 Select a technology page from the sidebar to begin.**
    """
)

st.info(
    "💡 Feed conditions are shared across all pages via session state — "
    "changing them on one page updates the calculation everywhere."
)